displayName=Revenant Gear Checker
author=Spiderkill93 (hcim.net)
description=Shows whether your gear is set up correctly to safespot revenants
tags=rev,revenant,safespot,wilderness,hcim
plugins=com.revsafespot.RevSafespotPlugin
